baseURL: 'https://salamandra-app.com/'
languageCode: en-us
title: Salamandra App
theme: custom-PaperMod
params:
  defaultTheme: dark
  disableThemeToggle: true
  profileMode:
    enabled: true
    title: "Salamandra App" # optional default will be site title
    subtitle: ""
    imageUrl: "images/salamander_noBackground.png"
    imageTitle: "<title of image as alt>"
    imageWidth: 300
    imageHeight: 300
    buttons:
      - name: Welcome
        url: "/home"
      - name: Features
        url: "/features"
      - name: About Us
        url: "/about"

  socialIcons:
    - name: "github"
      url: "https://github.com/SalamandraApp"
