baseURL: 'https://salamandra-app.com/'
languageCode: en-us
title: Salamandra App
theme: custom-PaperMod
params:
  defaultTheme: dark
  disableThemeToggle: true
  profileMode:
    enabled: true
    title: "Salamandra App" # optional default will be site title
    subtitle: ""
    imageUrl: "images/salamander_noBackground.png" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 500
    imageHeight: 500
    buttons:
      - name: Home
        url: "/home"
      - name: About Us
        url: "/about"

  socialIcons:
    - name: "github"
      url: "https://github.com/SalamandraApp"
